import { sql } from '@vercel/postgres';

async function resetDB() {
    await sql`DROP TABLE IF EXISTS project_ideas;`;
    await sql`CREATE TABLE project_ideas(
            id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            title varchar(100) NOT NULL,
            description varchar(100) NOT NULL
        );`;
    await sql`INSERT INTO project_ideas (title, description) VALUES
        ('A project ideas website', 'A website for people to post various project ideas');`;
    await sql`INSERT INTO project_ideas (title, description) VALUES
        ('Guess the Cassette Beast', 'A website for people to guess a Cassette Beast');`;
}

resetDB();